; This file was auto-generated by drush_make
core = 7.x

api = 2

; Modules
projects[admin_menu][version] = "3.x-dev"

projects[advanced_help][version] = "1.x-dev"

projects[colortheme][version] = "1.0"

projects[ctools][version] = "1.x-dev"

projects[captcha][version] = "1.x-dev"

; Modules
projects[devel][version] = "1.x-dev"

projects[diff][version] = "1.x-dev"

projects[emptyparagraphkiller][version] = "1.x-dev"

projects[entity][version] = "1.x-dev"

projects[entitycache][version] = "1.0"

projects[features][version] = "1.x-dev"

projects[git_deploy][version] = "1.x-dev"

projects[image_resize_filter][version] = "1.12"

projects[insert][version] = "1.1"

projects[libraries][version] = "2.x-dev"

projects[mongodb][version] = "1.0-beta2"

projects[references][version] = "2.x-dev"

projects[pathauto][version] = "1.x-dev"

projects[pathologic][version] = "1.1"

projects[realname][version] = "1.0-rc1"

projects[rules][version] = "2.0-beta1"

projects[security_review][version] = "1.x-dev"

projects[skinr][version] = "2.x-dev"

; Modules
projects[taxonomy_manager][version] = "1.x-dev"

projects[token][version] = "1.x-dev"

projects[variablecheck][version] = "1.1"

projects[views][version] = "3.x-dev"

; Themes
projects[sky][version] = "1.x-dev"
projects[rootcandy][version] = "1.x-dev"

; Libraries
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6/ckeditor_3.6.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][destination] = "library"

libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox.git"
libraries[colorbox][download][revision] = "4967ef9c24b4b2bccf15"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://dl.dropbox.com/u/22795799/superfish-library-for-drupal-v1.zip"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

